version: "3"

networks:
  back:

services:
  data-engineering:
    container_name: data-engineering
    build: ./data_engineering
    expose:
      - "5001"
    networks:
      - back

  database:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: signalements_utilisateurs
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/signalements.sql:/docker-entrypoint-initdb.d/signalements.sql
    networks:
      - back

  backend:
    container_name: backend
    build: ./backend
    expose:
      - "3001"
    depends_on:
      - database
    networks:
      - back

  frontend:
    container_name: frontend
    build: ./frontend
    expose:
      - "3000"
    networks:
      - back

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - backend
      - frontend
      - data-engineering
    ports:
      - "1234:22"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - back

volumes:
  postgres-data:
